Fix emailService.sendEmail call signature
BUGFIX: Build Failure - TypeScript Error

Fixed incorrect sendEmail usage:
- Changed from positional arguments to object parameter
- Correct: sendEmail({ to, subject, html })
- Incorrect: sendEmail(to, subject, html)

Error: TS2554: Expected 1 arguments, but got 3

File: src/services/refundService.ts
Line: 176-180